app/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :products
  resources :home, only: [:index]
#  mount RbacRls::Engine => :rbac_rls


end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  primary_abstract_class
end

app/app/models/product.rb
class Product < ApplicationRecord
end

app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index

    # @products = ApplicationRecord.with_user_id(current_user.id) do
    #   Product.all.to_a
    # end

    @products = Product.all

    # debugger
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.owner_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|

      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :value, :description)
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/ecommerce_benchmarks_helper.rb
module EcommerceBenchmarksHelper
end

app/app/helpers/home_helper.rb
module HomeHelper
end

app/app/helpers/products_helper.rb
module ProductsHelper
end

app/app/views/home/index.html.erb
<div class="container">
  <h1> Well come !! </h1>
</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
<head>
  <title>InventoryControl</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<% if signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Example To Teste Rbac RLS gem </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Home", home_index_path, class: 'nav-link active' %>
          <%= link_to "Products", products_path, class: 'nav-link' %>
          <span>
          </span>
          <%= button_to 'Exit', destroy_user_session_path, class: 'nav-link ', method: :delete %>
        </div>
      </div>
    </div>
  </nav>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
</body>
</html>

app/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/app/views/products/_product.html.erb
<tr id="<%= dom_id product %>">
  <td>
    <%= product.name %>
  </td>

  <td>
    <%= product.value %>
  </td>

  <td>
    <%= product.description %>
  </td>
  <td>
  <td>
    <%= button_to "Destroy this product", product, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <table class="table table-responsive">
    <tr>
      <th>NAME</th>
      <th>VALUE</th>
      <th>DESCRIPTION</th>
      <th>ACTIONS</th>
    </tr>
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </table>
</div>

<%= link_to "New product", new_product_path %>

app/app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>